version: "3"

services:
  app:
    build:
      context: app
    ports:
      - "5000"
    deploy:
      replicas: 3

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app